### ISSUE TITLE
Exporter not working

### ISSUE THREAD

**Issue by glpfloss** [prayagsingh/prometheus-jicofo-exporter#1]
Hi prayagsingh, first of all, thank you for your work on this

We've been testing your exporter but unfortunately, when we try to integrate with Prometheus, it marks as DOWN with error "expected value after metric, got "MNAME""

If we do a curl against the exporter looks good, could you help us?

Attaching curl output 
[jicofo.output.txt](https://github.com/prayagsingh/prometheus-jicofo-exporter/files/6988755/jicofo.output.txt)

EDIT: checking with promtool, looks like issue is with jitsi_xmpp_service {}

"error while linting: text format parsing error in line 3: expected float as value, got """

Thank you

**Comment by prayagsingh** [comment]
Thanks for reporting @glpfloss
 sure I'll look into it.

**Comment by prayagsingh** [comment]
@glpfloss Can you please try it now?

**Comment by glpfloss** [comment]
@prayagsingh thank you so much, tried docker image with tag 1.2.0 and works fine!
