### ISSUE TITLE
Wich JVB exporter do u use?

### ISSUE THREAD

**Issue by psi-4ward** [prayagsingh/prometheus-jicofo-exporter#67]
Hi,
I've found your **nice** Jicofo exporter. May I ask which one you use for the Videobridge?

Cause: I didn't find a _good_ one

**Comment by prayagsingh** [comment]
Hey @psi-4ward, I used Systemli [videobridge]( https://github.com/systemli/prometheus-jitsi-meet-exporter) exporter.
